In [40]:
import pandas as pd
import json

In [41]:
file = pd.read_csv('https://raw.githubusercontent.com/codedex-io/datasets/84527e3fb09b0f8cb028901d9d7a9874133ee662/pokemon/pokemon.csv')

In [42]:
file

,pokedex_number,name,type1,type2,attack,defense,speed
0,1,Bulbasaur,Grass,Poison,49,49,45
1,2,Ivysaur,Grass,Poison,62,63,60
2,3,Venusaur,Grass,Poison,82,83,80
3,3,VenusaurMega Venusaur,Grass,Poison,100,123,80
4,4,Charmander,Fire,NaN,52,43,65
...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,100,150,50
796,719,DiancieMega Diancie,Rock,Fairy,160,110,110
797,720,HoopaHoopa Confined,Psychic,Ghost,110,60,70
798,720,HoopaHoopa Unbound,Psychic,Dark,160,60,80
799,721,Volcanion,Fire,Water,110,120,70

In [43]:
raw_json = {
  "data": {
    "videos": [
      {
        "id": "7080213458555737986",
        "title": "3 Projects You Can Code in a Day",
        "video_description": "Happy coding & gaming!",
        "duration": 2,
        "create_time": 1633823999,
      },
      {
        "id": "7080213458555737987",
        "title": "3 New Reads on Codedex",
        "video_description": "From new website features to project tutorials",
        "duration": 5,
        "create_time": 1633830000,
      }
    ],
    "has_more": True,
  },
  "error": {
    "code": "0",
    "message": "ok"
  }
}

In [44]:
raw_json

{'data': {'videos': [{'id': '7080213458555737986',
    'title': '3 Projects You Can Code in a Day',
    'video_description': 'Happy coding & gaming!',
    'duration': 2,
    'create_time': 1633823999},
   {'id': '7080213458555737987',
    'title': '3 New Reads on Codedex',
    'video_description': 'From new website features to project tutorials',
    'duration': 5,
    'create_time': 1633830000}],
  'has_more': True},
 'error': {'code': '0', 'message': 'ok'}}

In [45]:
df = pd.DataFrame(raw_json['data']['videos'])

In [46]:
df

,id,title,video_description,duration,create_time
0,7080213458555737986,3 Projects You Can Code in a Day,Happy coding & gaming!,2,1633823999
1,7080213458555737987,3 New Reads on Codedex,From new website features to project tutorials,5,1633830000

In [48]:
with open('movies.json', 'r') as f:
    raw_json = json.load(f)

df = pd.DataFrame(raw_json['movies'])

In [49]:
df

             title  year      genre  rating
0         Parasite  2019   Thriller     8.5
1      Oppenheimer  2023  Biography     8.6
2     Interstellar  2014     Sci-Fi     8.7
3  The Dark Knight  2008     Action     9.0
4        Inception  2010     Sci-Fi     8.8