Instructions
Everyone is chronically on their phone these days. 📱👀

We've created a DataFrame named apps that contains (fictional) data about popular apps:

Call .head() or .tail() to see only the start or end of the DataFrame.
Call .info(). Are there any missing values?
Call .describe(). What is the average number of downloads?
Do you feel more confident in your understanding of the data now?

In [1]:
import pandas as pd

In [2]:
# Popular mobile apps
app_data = {
  'app_name': [
    'YouTube', 'TikTok', 'Instagram', 'Spotify', 'Duolingo', 
    'Twitter', 'Headspace', 'Discord', 'Depop'
  ],
  'category': [
    'Video', 'Social Media', 'Social Media', 'Music', 'Education',
    'Social Media', 'Health', 'Communication', 'Shopping'
  ],
  'rating': [
    4.7, 4.6, 4.5, 4.6, 4.7,
    4.3, None, 4.7, 4.4
  ],
  'downloads_millions': [
    5000, 3000, 3500, 2000, None,
    1500, 500, 600, 200
  ]
}

In [3]:
# Create the DataFrame
apps = pd.DataFrame(app_data)

In [4]:
apps.head()

    app_name      category  rating  downloads_millions
0    YouTube         Video     4.7              5000.0
1     TikTok  Social Media     4.6              3000.0
2  Instagram  Social Media     4.5              3500.0
3    Spotify         Music     4.6              2000.0
4   Duolingo     Education     4.7                 NaN

In [5]:
apps.tail()

    app_name       category  rating  downloads_millions
4   Duolingo      Education     4.7                 NaN
5    Twitter   Social Media     4.3              1500.0
6  Headspace         Health     NaN               500.0
7    Discord  Communication     4.7               600.0
8      Depop       Shopping     4.4               200.0

In [6]:
apps.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 4 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   app_name            9 non-null      object
 1   category            9 non-null      object
 2   rating              8 non-null      float64
 3   downloads_millions  8 non-null      float64
dtypes: float64(2), object(2)
memory usage: 420.0+ bytes

In [7]:
apps.describe()

         rating  downloads_millions
count  8.000000             8.00000
mean   4.562500          2037.50000
std    0.150594          1687.71824
min    4.300000           200.00000
25%    4.475000           575.00000
50%    4.600000          1750.00000
75%    4.700000          3125.00000
max    4.700000          5000.00000